apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: vroom
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: vroom
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vroom-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              value: vroom
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: vroom
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
