apiVersion: v1
kind: Secret
metadata:
  name: vroom-secrets
  namespace: vroom
type: Opaque
stringData:
  jwt-secret: changeme
  postgres-password: vroom
  database-url: postgres://vroom:vroom@postgres:5432/vroom
